// Download + optimize the chosen iNaturalist photos and emit a typed manifest.
//
//   node scripts/build-photos.mjs
//
// Reads scripts/photos-raw.json (from fetch-photos.mjs), downloads each medium
// image into public/photos/<slug>.jpg (resized/recompressed with macOS `sips`),
// and writes src/data/photos.ts mapping scientific name -> { src, credit, ... }.

import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const RAW = path.join(__dirname, "photos-raw.json");
const PHOTO_DIR = path.join(ROOT, "public/photos");
const MANIFEST = path.join(ROOT, "src/data/photos.ts");
const UA = "native-plants-for-bees/1.0 (https://github.com/gyndok/bee_plants)";

const slug = (s) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

fs.mkdirSync(PHOTO_DIR, { recursive: true });
const raw = JSON.parse(fs.readFileSync(RAW, "utf8"));
const manifest = {};
let saved = 0, skipped = 0;

for (const r of raw) {
  if (!r.medium || !r.status?.startsWith("ok")) {
    skipped++;
    continue;
  }
  const id = slug(r.scientific);
  const file = path.join(PHOTO_DIR, `${id}.jpg`);
  try {
    if (!fs.existsSync(file)) {
      const res = await fetch(r.medium, { headers: { "User-Agent": UA } });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const buf = Buffer.from(await res.arrayBuffer());
      fs.writeFileSync(file, buf);
      // Cap longest side at 500px and recompress (built-in macOS tool).
      execFileSync("sips", [
        "-s", "format", "jpeg",
        "-s", "formatOptions", "72",
        "-Z", "500",
        file, "--out", file,
      ], { stdio: "ignore" });
    }
    manifest[r.scientific] = {
      src: `/photos/${id}.jpg`,
      credit: (r.attribution || "iNaturalist").replace(/\s+/g, " ").trim(),
      license: r.license || "",
      sourceUrl: r.sourceUrl || "",
    };
    saved++;
  } catch (e) {
    console.log(`  skip ${r.scientific}: ${e.message}`);
    skipped++;
  }
}

const body =
  `// Auto-generated by scripts/build-photos.mjs — do not edit by hand.\n` +
  `// Plant photos from iNaturalist (Creative Commons licensed). Keyed by\n` +
  `// scientific name as it appears in plants.ts.\n\n` +
  `export type PlantPhoto = {\n` +
  `  src: string;\n  credit: string;\n  license: string;\n  sourceUrl: string;\n};\n\n` +
  `export const photos: Record<string, PlantPhoto> = ${JSON.stringify(manifest, null, 2)};\n`;
fs.writeFileSync(MANIFEST, body);

const totalKB = fs
  .readdirSync(PHOTO_DIR)
  .reduce((n, f) => n + fs.statSync(path.join(PHOTO_DIR, f)).size, 0) / 1024;
console.log(`Saved ${saved} photos, skipped ${skipped}.`);
console.log(`public/photos total: ${(totalKB / 1024).toFixed(1)} MB`);
console.log(`Manifest -> ${path.relative(ROOT, MANIFEST)}`);
