// Auto-generated by scripts/build-photos.mjs — do not edit by hand.
// Plant photos from iNaturalist (Creative Commons licensed). Keyed by
// scientific name as it appears in plants.ts.

export type PlantPhoto = {
  src: string;
  credit: string;
  license: string;
  sourceUrl: string;
};

export const photos: Record<string, PlantPhoto> = {
  "Gelsemium sempervirens": {
    "src": "/photos/gelsemium-sempervirens.jpg",
    "credit": "(c) dogtooth77, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/83070"
  },
  "Hibiscus martianus": {
    "src": "/photos/hibiscus-martianus.jpg",
    "credit": "(c) CARLOS VELAZCO, some rights reserved (CC BY-NC), uploaded by CARLOS VELAZCO",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/163769"
  },
  "Populus deltoides": {
    "src": "/photos/populus-deltoides.jpg",
    "credit": "(c) JanetandPhil, some rights reserved (CC BY-NC-ND)",
    "license": "cc-by-nc-nd",
    "sourceUrl": "https://www.inaturalist.org/taxa/52119"
  },
  "Celtis laevigata": {
    "src": "/photos/celtis-laevigata.jpg",
    "credit": "(c) Becky Brenner, some rights reserved (CC BY-NC), uploaded by Becky Brenner",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/81792"
  },
  "Aphanostephus skirrhobasis": {
    "src": "/photos/aphanostephus-skirrhobasis.jpg",
    "credit": "(c) Kimberlie Sasan, some rights reserved (CC BY-ND), uploaded by Kimberlie Sasan",
    "license": "cc-by-nd",
    "sourceUrl": "https://www.inaturalist.org/taxa/120486"
  },
  "Crataegus opaca": {
    "src": "/photos/crataegus-opaca.jpg",
    "credit": "(c) Pauline Singleton, some rights reserved (CC BY-NC), uploaded by Pauline Singleton",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/161056"
  },
  "Prunus mexicana": {
    "src": "/photos/prunus-mexicana.jpg",
    "credit": "(c) amy_buthod, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/128755"
  },
  "Salvia coccinea": {
    "src": "/photos/salvia-coccinea.jpg",
    "credit": "no rights reserved, uploaded by Brady Reed",
    "license": "cc0",
    "sourceUrl": "https://www.inaturalist.org/taxa/128652"
  },
  "Oenothera speciosa": {
    "src": "/photos/oenothera-speciosa.jpg",
    "credit": "(c) Judith Ellen Lopez, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/48625"
  },
  "Sophora secundiflora": {
    "src": "/photos/sophora-secundiflora.jpg",
    "credit": "(c) lucio101, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/499559"
  },
  "Hymenocallis liriosme": {
    "src": "/photos/hymenocallis-liriosme.jpg",
    "credit": "(c) jcdonaho, some rights reserved (CC BY-NC), uploaded by jcdonaho",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/126794"
  },
  "Carpinus caroliniana": {
    "src": "/photos/carpinus-caroliniana.jpg",
    "credit": "(c) ThePrairiePreacher, some rights reserved (CC BY-NC), uploaded by ThePrairiePreacher",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/54768"
  },
  "Liquidambar styraciflua": {
    "src": "/photos/liquidambar-styraciflua.jpg",
    "credit": "(c) Randy Puckett, some rights reserved (CC BY-NC), uploaded by Randy Puckett",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/49658"
  },
  "Platanus occidentalis": {
    "src": "/photos/platanus-occidentalis.jpg",
    "credit": "no rights reserved, uploaded by Andy Wilson",
    "license": "cc0",
    "sourceUrl": "https://www.inaturalist.org/taxa/49662"
  },
  "Asclepias asperula": {
    "src": "/photos/asclepias-asperula.jpg",
    "credit": "(c) Russ Hoverman, some rights reserved (CC BY-NC), uploaded by Russ Hoverman",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/62298"
  },
  "Salvia greggii": {
    "src": "/photos/salvia-greggii.jpg",
    "credit": "(c) David Mercado-Morales, some rights reserved (CC BY-NC), uploaded by David Mercado-Morales",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/168380"
  },
  "Prunus serotina": {
    "src": "/photos/prunus-serotina.jpg",
    "credit": "(c) Danny Barron, some rights reserved (CC BY-NC-ND)",
    "license": "cc-by-nc-nd",
    "sourceUrl": "https://www.inaturalist.org/taxa/54834"
  },
  "Melampodium leucanthum": {
    "src": "/photos/melampodium-leucanthum.jpg",
    "credit": "(c) stelluti, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/82469"
  },
  "Sisyrinchium angustifolium": {
    "src": "/photos/sisyrinchium-angustifolium.jpg",
    "credit": "(c) Patrick Coin, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/49916"
  },
  "Tradescantia ohiensis": {
    "src": "/photos/tradescantia-ohiensis.jpg",
    "credit": "(c) Michael J. Papay, some rights reserved (CC BY), uploaded by Michael J. Papay",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/79383"
  },
  "Hypoxis hirsuta": {
    "src": "/photos/hypoxis-hirsuta.jpg",
    "credit": "(c) Bart Jones, some rights reserved (CC BY-NC), uploaded by Bart Jones",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/81797"
  },
  "Erythrina herbacea": {
    "src": "/photos/erythrina-herbacea.jpg",
    "credit": "(c) Dwight Bohlmeyer, some rights reserved (CC BY-NC), uploaded by Dwight Bohlmeyer",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/128717"
  },
  "Lonicera sempervirens": {
    "src": "/photos/lonicera-sempervirens.jpg",
    "credit": "(c) Laura Kimberly, some rights reserved (CC BY-NC), uploaded by Laura Kimberly",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/119809"
  },
  "Erigeron procumbens": {
    "src": "/photos/erigeron-procumbens.jpg",
    "credit": "(c) victorv17, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/162519"
  },
  "Bignonia capreolata": {
    "src": "/photos/bignonia-capreolata.jpg",
    "credit": "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/67823"
  },
  "Oenothera laciniata": {
    "src": "/photos/oenothera-laciniata.jpg",
    "credit": "(c) Clifton Albrecht, some rights reserved (CC BY-NC), uploaded by Clifton Albrecht",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/78243"
  },
  "Phlox drummondii": {
    "src": "/photos/phlox-drummondii.jpg",
    "credit": "(c) mlhradio, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/126177"
  },
  "Cercis canadensis": {
    "src": "/photos/cercis-canadensis.jpg",
    "credit": "(c) dbarronoss, some rights reserved (CC BY-NC-ND)",
    "license": "cc-by-nc-nd",
    "sourceUrl": "https://www.inaturalist.org/taxa/48502"
  },
  "Castilleja indivisa": {
    "src": "/photos/castilleja-indivisa.jpg",
    "credit": "(c) Aidan Campos, some rights reserved (CC BY-NC), uploaded by Aidan Campos",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/123956"
  },
  "Vaccinium arboreum": {
    "src": "/photos/vaccinium-arboreum.jpg",
    "credit": "(c) John C., some rights reserved (CC BY-NC), uploaded by John C.",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/81818"
  },
  "Cornus florida": {
    "src": "/photos/cornus-florida.jpg",
    "credit": "(c) Ryan_Diener, some rights reserved (CC BY-NC), uploaded by Ryan_Diener",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/54777"
  },
  "Tetraneuris scaposa": {
    "src": "/photos/tetraneuris-scaposa.jpg",
    "credit": "(c) Jerry Oldenettel, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/132723"
  },
  "Conoclinium dissectum": {
    "src": "/photos/conoclinium-dissectum.jpg",
    "credit": "(c) Josh*m, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/288658"
  },
  "Penstemon tenuis": {
    "src": "/photos/penstemon-tenuis.jpg",
    "credit": "(c) Josh*m, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/166449"
  },
  "Verbena xutha": {
    "src": "/photos/verbena-xutha.jpg",
    "credit": "(c) blake hendon, some rights reserved (CC BY-NC), uploaded by blake hendon",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/170161"
  },
  "Calyptocarpus vialis": {
    "src": "/photos/calyptocarpus-vialis.jpg",
    "credit": "no rights reserved, uploaded by 葉子",
    "license": "cc0",
    "sourceUrl": "https://www.inaturalist.org/taxa/84405"
  },
  "Salvia lyrata": {
    "src": "/photos/salvia-lyrata.jpg",
    "credit": "(c) dogtooth77, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/64093"
  },
  "Viola sororia": {
    "src": "/photos/viola-sororia.jpg",
    "credit": "(c) Rosie Green, some rights reserved (CC BY-NC-ND), uploaded by Rosie Green",
    "license": "cc-by-nc-nd",
    "sourceUrl": "https://www.inaturalist.org/taxa/82816"
  },
  "Crataegus marshallii": {
    "src": "/photos/crataegus-marshallii.jpg",
    "credit": "(c) skelico, some rights reserved (CC BY), uploaded by skelico",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/67818"
  },
  "Erigeron philadelphicus": {
    "src": "/photos/erigeron-philadelphicus.jpg",
    "credit": "(c) Jimmy Smith, some rights reserved (CC BY-NC-ND)",
    "license": "cc-by-nc-nd",
    "sourceUrl": "https://www.inaturalist.org/taxa/67820"
  },
  "Rivina humilis": {
    "src": "/photos/rivina-humilis.jpg",
    "credit": "(c) Meghan Cassidy, some rights reserved (CC BY-SA), uploaded by Meghan Cassidy",
    "license": "cc-by-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/133291"
  },
  "Ilex decidua": {
    "src": "/photos/ilex-decidua.jpg",
    "credit": "(c) Thomas Shahan, some rights reserved (CC BY-NC), uploaded by Thomas Shahan",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/120006"
  },
  "Mimosa strigillosa": {
    "src": "/photos/mimosa-strigillosa.jpg",
    "credit": "(c) Stephanie, some rights reserved (CC BY-NC), uploaded by Stephanie",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/165400"
  },
  "Herbertia lahue": {
    "src": "/photos/herbertia-lahue.jpg",
    "credit": "(c) prairie_celestial, some rights reserved (CC BY-NC), uploaded by prairie_celestial",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/163683"
  },
  "Glandularia bipinnatifida": {
    "src": "/photos/glandularia-bipinnatifida.jpg",
    "credit": "(c) Katelyn Rose, some rights reserved (CC BY-NC), uploaded by Katelyn Rose",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/125675"
  },
  "Aesculus pavia": {
    "src": "/photos/aesculus-pavia.jpg",
    "credit": "(c) Devin Moon, some rights reserved (CC BY-NC), uploaded by Devin Moon",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/81708"
  },
  "Morus rubra": {
    "src": "/photos/morus-rubra.jpg",
    "credit": "(c) kwillard, some rights reserved (CC BY-NC), uploaded by kwillard",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/54801"
  },
  "Sassafras albidum": {
    "src": "/photos/sassafras-albidum.jpg",
    "credit": "(c) Tom Potterfield, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/54795"
  },
  "Stachys coccinea": {
    "src": "/photos/stachys-coccinea.jpg",
    "credit": "(c) Ron Savage, some rights reserved (CC BY-NC-SA), uploaded by Ron Savage",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/146598"
  },
  "Verbena halei": {
    "src": "/photos/verbena-halei.jpg",
    "credit": "(c) Steve Harbula, some rights reserved (CC BY-NC), uploaded by Steve Harbula",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/170148"
  },
  "Rubus trivialis": {
    "src": "/photos/rubus-trivialis.jpg",
    "credit": "no rights reserved, uploaded by lanechaffin",
    "license": "cc0",
    "sourceUrl": "https://www.inaturalist.org/taxa/69714"
  },
  "Lindera benzoin": {
    "src": "/photos/lindera-benzoin.jpg",
    "credit": "(c) Sandy Wolkenberg, some rights reserved (CC BY), uploaded by Sandy Wolkenberg",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/54793"
  },
  "Calylophus berlandieri": {
    "src": "/photos/calylophus-berlandieri.jpg",
    "credit": "(c) Conor McMahon, some rights reserved (CC BY-NC), uploaded by Conor McMahon",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/1616205"
  },
  "Callirhoe leiocarpa": {
    "src": "/photos/callirhoe-leiocarpa.jpg",
    "credit": "(c) Ron Stephens, some rights reserved (CC BY-NC), uploaded by Ron Stephens",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/159672"
  },
  "Lupinus texensis": {
    "src": "/photos/lupinus-texensis.jpg",
    "credit": "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/49564"
  },
  "Diospyros texana": {
    "src": "/photos/diospyros-texana.jpg",
    "credit": "(c) Gravitywave, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/120505"
  },
  "Halesia diptera": {
    "src": "/photos/halesia-diptera.jpg",
    "credit": "(c) Laura Clark, some rights reserved (CC BY), uploaded by Laura Clark",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/163505"
  },
  "Elymus virginicus": {
    "src": "/photos/elymus-virginicus.jpg",
    "credit": "(c) Jeff Skrentny, some rights reserved (CC BY-NC), uploaded by Jeff Skrentny",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/126873"
  },
  "Morella cerifera": {
    "src": "/photos/morella-cerifera.jpg",
    "credit": "(c) Homer Edward Price, some rights reserved (CC BY)",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/119956"
  },
  "Carex perdentata": {
    "src": "/photos/carex-perdentata.jpg",
    "credit": "(c) Eric Keith, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/observations/281899142"
  },
  "Tradescantia occidentalis": {
    "src": "/photos/tradescantia-occidentalis.jpg",
    "credit": "(c) Tabby Brobston, some rights reserved (CC BY-NC), uploaded by Tabby Brobston",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/121785"
  },
  "Callirhoe involucrata": {
    "src": "/photos/callirhoe-involucrata.jpg",
    "credit": "(c) Pauline Singleton, some rights reserved (CC BY-NC), uploaded by Pauline Singleton",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/127941"
  },
  "Iris brevicaulis": {
    "src": "/photos/iris-brevicaulis.jpg",
    "credit": "(c) Andy Newman, some rights reserved (CC BY-NC), uploaded by Andy Newman",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/164124"
  },
  "Asclepias oenotheroides": {
    "src": "/photos/asclepias-oenotheroides.jpg",
    "credit": "(c) Don Verser, some rights reserved (CC BY-NC), uploaded by Don Verser",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/158753"
  },
  "Tilia americana": {
    "src": "/photos/tilia-americana.jpg",
    "credit": "(c) Anita, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/54854"
  },
  "Ostrya virginiana": {
    "src": "/photos/ostrya-virginiana.jpg",
    "credit": "(c) Patrick Coin, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/54771"
  },
  "Helenium amarum": {
    "src": "/photos/helenium-amarum.jpg",
    "credit": "(c) Dan Vickers, some rights reserved (CC BY), uploaded by Dan Vickers",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/77348"
  },
  "Nyssa sylvatica": {
    "src": "/photos/nyssa-sylvatica.jpg",
    "credit": "(c) mountainad82, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/54802"
  },
  "Salix nigra": {
    "src": "/photos/salix-nigra.jpg",
    "credit": "(c) sehnature, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/54847"
  },
  "Bouteloua dactyloides": {
    "src": "/photos/bouteloua-dactyloides.jpg",
    "credit": "(c) Sam Kieschnick, some rights reserved (CC BY), uploaded by Sam Kieschnick",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/288038"
  },
  "Delphinium carolinianum": {
    "src": "/photos/delphinium-carolinianum.jpg",
    "credit": "(c) Royal Tyler, some rights reserved (CC BY-NC-SA), uploaded by Royal Tyler",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/161660"
  },
  "Carex cherokeensis": {
    "src": "/photos/carex-cherokeensis.jpg",
    "credit": "(c) georgiek32, some rights reserved (CC BY-NC), uploaded by georgiek32",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/135269"
  },
  "Dracopis amplexicaulis": {
    "src": "/photos/dracopis-amplexicaulis.jpg",
    "credit": "(c) Cassi, some rights reserved (CC BY-NC), uploaded by Cassi",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/200073"
  },
  "Diospyros virginiana": {
    "src": "/photos/diospyros-virginiana.jpg",
    "credit": "(c) Douglas Goldman, some rights reserved (CC BY-SA), uploaded by Douglas Goldman",
    "license": "cc-by-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/83435"
  },
  "Dalea compacta": {
    "src": "/photos/dalea-compacta.jpg",
    "credit": "(c) Judith Ellen Lopez, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/139274"
  },
  "Symphoricarpos orbiculatus": {
    "src": "/photos/symphoricarpos-orbiculatus.jpg",
    "credit": "(c) Meghan Cassidy, some rights reserved (CC BY-SA), uploaded by Meghan Cassidy",
    "license": "cc-by-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/128838"
  },
  "Verbesina encelioides": {
    "src": "/photos/verbesina-encelioides.jpg",
    "credit": "(c) Christine Sydes, some rights reserved (CC BY-NC), uploaded by Christine Sydes",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/79495"
  },
  "Tripsacum dactyloides": {
    "src": "/photos/tripsacum-dactyloides.jpg",
    "credit": "(c) samlutfy, some rights reserved (CC BY), uploaded by samlutfy",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/126563"
  },
  "Tecoma stans": {
    "src": "/photos/tecoma-stans.jpg",
    "credit": "(c) lyndahicklin_05, some rights reserved (CC BY-NC), uploaded by lyndahicklin_05",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/48363"
  },
  "Amorpha fruticosa": {
    "src": "/photos/amorpha-fruticosa.jpg",
    "credit": "(c) Peter May, some rights reserved (CC BY-NC), uploaded by Peter May",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/57356"
  },
  "Chionanthus virginicus": {
    "src": "/photos/chionanthus-virginicus.jpg",
    "credit": "(c) Arthur T. LaBar, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/54654"
  },
  "Aquilegia chrysantha": {
    "src": "/photos/aquilegia-chrysantha.jpg",
    "credit": "(c) James Gaither, some rights reserved (CC BY-NC-ND)",
    "license": "cc-by-nc-nd",
    "sourceUrl": "https://www.inaturalist.org/taxa/121784"
  },
  "Fraxinus pennsylvanica": {
    "src": "/photos/fraxinus-pennsylvanica.jpg",
    "credit": "(c) Keith Kanoti, Maine Forest Service, USA, some rights reserved (CC BY)",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/54808"
  },
  "Asclepias viridis": {
    "src": "/photos/asclepias-viridis.jpg",
    "credit": "(c) sonnia hill, some rights reserved (CC BY)",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/60946"
  },
  "Scutellaria ovata": {
    "src": "/photos/scutellaria-ovata.jpg",
    "credit": "(c) Jenny Hollis Miller, some rights reserved (CC BY-NC), uploaded by Jenny Hollis Miller",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/82531"
  },
  "Coreopsis lanceolata": {
    "src": "/photos/coreopsis-lanceolata.jpg",
    "credit": "(c) Joan Knapp, some rights reserved (CC BY-ND), uploaded by Joan Knapp",
    "license": "cc-by-nd",
    "sourceUrl": "https://www.inaturalist.org/taxa/76444"
  },
  "Monarda lindheimerii": {
    "src": "/photos/monarda-lindheimerii.jpg",
    "credit": "(c) Bill Freiheit, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/observations/26029147"
  },
  "Gaura lindheimeri / Oenothera lindheimeri": {
    "src": "/photos/gaura-lindheimeri-oenothera-lindheimeri.jpg",
    "credit": "(c) Grant Reed, some rights reserved (CC BY-NC), uploaded by Grant Reed",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/590726"
  },
  "Salvia farinacea": {
    "src": "/photos/salvia-farinacea.jpg",
    "credit": "(c) Mauricio Mercadante, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/148006"
  },
  "Maclura pomifera": {
    "src": "/photos/maclura-pomifera.jpg",
    "credit": "(c) hilliri, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/58205"
  },
  "Coreopsis tinctoria": {
    "src": "/photos/coreopsis-tinctoria.jpg",
    "credit": "(c) Jenn Drummond, some rights reserved (CC BY-NC), uploaded by Jenn Drummond",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/76445"
  },
  "Polytaenia texana": {
    "src": "/photos/polytaenia-texana.jpg",
    "credit": "(c) Chuck Sexton, some rights reserved (CC BY-NC), uploaded by Chuck Sexton",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/167284"
  },
  "Penstemon cobaea": {
    "src": "/photos/penstemon-cobaea.jpg",
    "credit": "(c) Eric Hunt, some rights reserved (CC BY-SA)",
    "license": "cc-by-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/142655"
  },
  "Echinacea purpurea": {
    "src": "/photos/echinacea-purpurea.jpg",
    "credit": "(c) Virginia (Ginny) Sanderson, some rights reserved (CC BY-NC-ND)",
    "license": "cc-by-nc-nd",
    "sourceUrl": "https://www.inaturalist.org/taxa/48627"
  },
  "Passiflora incarnata": {
    "src": "/photos/passiflora-incarnata.jpg",
    "credit": "(c) Alex Abair, some rights reserved (CC BY), uploaded by Alex Abair",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/51453"
  },
  "Rudbeckia grandiflora": {
    "src": "/photos/rudbeckia-grandiflora.jpg",
    "credit": "(c) timarcus, some rights reserved (CC BY-NC), uploaded by timarcus",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/168200"
  },
  "Cornus drummondii": {
    "src": "/photos/cornus-drummondii.jpg",
    "credit": "(c) Arb O'Retum, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/54776"
  },
  "Viburnum rufidulum": {
    "src": "/photos/viburnum-rufidulum.jpg",
    "credit": "(c) Jennifer Ogle, some rights reserved (CC BY-NC), uploaded by Jennifer Ogle",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/81801"
  },
  "Echinacea sanguinea": {
    "src": "/photos/echinacea-sanguinea.jpg",
    "credit": "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/162169"
  },
  "Ageratina havanensis": {
    "src": "/photos/ageratina-havanensis.jpg",
    "credit": "(c) James Bailey, some rights reserved (CC BY-NC), uploaded by James Bailey",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/158108"
  },
  "Magnolia grandiflora": {
    "src": "/photos/magnolia-grandiflora.jpg",
    "credit": "(c) 潘立傑 LiChieh Pan, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/83074"
  },
  "Monarda punctata": {
    "src": "/photos/monarda-punctata.jpg",
    "credit": "(c) Mark Kluge, some rights reserved (CC BY-NC), uploaded by Mark Kluge",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/118776"
  },
  "Magnolia virginiana": {
    "src": "/photos/magnolia-virginiana.jpg",
    "credit": "(c) Patty Mitchum, some rights reserved (CC BY), uploaded by Patty Mitchum",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/127906"
  },
  "Bouteloua rigidiseta": {
    "src": "/photos/bouteloua-rigidiseta.jpg",
    "credit": "(c) Sam Kieschnick, some rights reserved (CC BY), uploaded by Sam Kieschnick",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/159359"
  },
  "Lantana urticoides / Lantana horrida": {
    "src": "/photos/lantana-urticoides-lantana-horrida.jpg",
    "credit": "(c) Chuck Sexton, some rights reserved (CC BY-NC), uploaded by Chuck Sexton",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/877372"
  },
  "Itea virginica": {
    "src": "/photos/itea-virginica.jpg",
    "credit": "(c) Tom Potterfield, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/83152"
  },
  "Nyssa aquatica": {
    "src": "/photos/nyssa-aquatica.jpg",
    "credit": "(c) Christopher David Benda，保留部分权利（CC BY-NC）, 由 Christopher David Benda 上传",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/165760"
  },
  "Achillea millefolium": {
    "src": "/photos/achillea-millefolium.jpg",
    "credit": "(c) philmb, some rights reserved (CC BY-NC), uploaded by philmb",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/1105043"
  },
  "Ilex vomitoria": {
    "src": "/photos/ilex-vomitoria.jpg",
    "credit": "(c) Laura Clark, some rights reserved (CC BY), uploaded by Laura Clark",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/119955"
  },
  "Baptisia sphaerocarpa": {
    "src": "/photos/baptisia-sphaerocarpa.jpg",
    "credit": "(c) Scott Buckel, some rights reserved (CC BY-NC), uploaded by Scott Buckel",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/128518"
  },
  "Merremia dissecta": {
    "src": "/photos/merremia-dissecta.jpg",
    "credit": "(c) Kenneth Bader, some rights reserved (CC BY-NC), uploaded by Kenneth Bader",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/907480"
  },
  "Plectocephalus americanus": {
    "src": "/photos/plectocephalus-americanus.jpg",
    "credit": "(c) Cosmic Cat, some rights reserved (CC BY-NC-ND), uploaded by Cosmic Cat",
    "license": "cc-by-nc-nd",
    "sourceUrl": "https://www.inaturalist.org/taxa/699778"
  },
  "Teucrium canadense": {
    "src": "/photos/teucrium-canadense.jpg",
    "credit": "(c) John G, some rights reserved (CC BY-NC), uploaded by John G",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/64547"
  },
  "Asclepias perennis": {
    "src": "/photos/asclepias-perennis.jpg",
    "credit": "(c) Andy Newman, some rights reserved (CC BY-NC), uploaded by Andy Newman",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/120152"
  },
  "Viburnum dentatum": {
    "src": "/photos/viburnum-dentatum.jpg",
    "credit": "(c) Ashwin Srinivasan, some rights reserved (CC BY), uploaded by Ashwin Srinivasan",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/82247"
  },
  "Sambucus nigra": {
    "src": "/photos/sambucus-nigra.jpg",
    "credit": "(c) Rison Thumboor, some rights reserved (CC BY-SA)",
    "license": "cc-by-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/1665961"
  },
  "Paspalum plicatulum": {
    "src": "/photos/paspalum-plicatulum.jpg",
    "credit": "(c) Bob Romero, some rights reserved (CC BY-NC), uploaded by Bob Romero",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/166191"
  },
  "Asclepias tuberosa": {
    "src": "/photos/asclepias-tuberosa.jpg",
    "credit": "(c) Michael J. Papay, some rights reserved (CC BY), uploaded by Michael J. Papay",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/47912"
  },
  "Lobelia cardinalis": {
    "src": "/photos/lobelia-cardinalis.jpg",
    "credit": "(c) Douglas Goldman, some rights reserved (CC BY-SA), uploaded by Douglas Goldman",
    "license": "cc-by-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/48038"
  },
  "Capsicum annuum": {
    "src": "/photos/capsicum-annuum.jpg",
    "credit": "(c) bigdannyb, some rights reserved (CC BY-NC), uploaded by bigdannyb",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/48514"
  },
  "Polanisia dodecandra": {
    "src": "/photos/polanisia-dodecandra.jpg",
    "credit": "no rights reserved",
    "license": "cc0",
    "sourceUrl": "https://www.inaturalist.org/taxa/78664"
  },
  "Hyptis alata": {
    "src": "/photos/hyptis-alata.jpg",
    "credit": "(c) Tina, some rights reserved (CC BY-NC), uploaded by Tina",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/132078"
  },
  "Engelmannia peristenia": {
    "src": "/photos/engelmannia-peristenia.jpg",
    "credit": "(c) Danny Barron, some rights reserved (CC BY-NC-ND)",
    "license": "cc-by-nc-nd",
    "sourceUrl": "https://www.inaturalist.org/taxa/127943"
  },
  "Sabal minor": {
    "src": "/photos/sabal-minor.jpg",
    "credit": "(c) Larry D. Moore, some rights reserved (CC BY)",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/81804"
  },
  "Setaria scheelei": {
    "src": "/photos/setaria-scheelei.jpg",
    "credit": "(c) turtlehugger, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/168888"
  },
  "Thelesperma filifolium": {
    "src": "/photos/thelesperma-filifolium.jpg",
    "credit": "(c) Philip Woods, some rights reserved (CC BY-NC), uploaded by Philip Woods",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/169675"
  },
  "Gleditsia triacanthos": {
    "src": "/photos/gleditsia-triacanthos.jpg",
    "credit": "(c) Dwight Bohlmeyer, some rights reserved (CC BY-NC), uploaded by Dwight Bohlmeyer",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/54797"
  },
  "Desmanthus illinoensis": {
    "src": "/photos/desmanthus-illinoensis.jpg",
    "credit": "(c) kcarrol2, some rights reserved (CC BY-NC), uploaded by kcarrol2",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/128701"
  },
  "Gaillardia pulchella": {
    "src": "/photos/gaillardia-pulchella.jpg",
    "credit": "(c) TexasEagle, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/51768"
  },
  "Arnoglossum reniforme": {
    "src": "/photos/arnoglossum-reniforme.jpg",
    "credit": "(c) Matthew Thompson, some rights reserved (CC BY-NC), uploaded by Matthew Thompson",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/359187"
  },
  "Gaillardia aestivalis": {
    "src": "/photos/gaillardia-aestivalis.jpg",
    "credit": "(c) mlhradio, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/133437"
  },
  "Monarda citriodora": {
    "src": "/photos/monarda-citriodora.jpg",
    "credit": "(c) Conor McMahon, some rights reserved (CC BY-NC), uploaded by Conor McMahon",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/122587"
  },
  "Baptisia bracteata": {
    "src": "/photos/baptisia-bracteata.jpg",
    "credit": "(c) Joshua, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/51722"
  },
  "Allium canadense": {
    "src": "/photos/allium-canadense.jpg",
    "credit": "(c) Mike B, some rights reserved (CC BY-SA), uploaded by Mike B",
    "license": "cc-by-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/126641"
  },
  "Ratibida columnifera": {
    "src": "/photos/ratibida-columnifera.jpg",
    "credit": "(c) Donna Pomeroy, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/observations/5959942"
  },
  "Echinacea angustifolia": {
    "src": "/photos/echinacea-angustifolia.jpg",
    "credit": "(c) Elaine White, some rights reserved (CC BY-NC), uploaded by Elaine White",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/162167"
  },
  "Eryngium yuccifolium": {
    "src": "/photos/eryngium-yuccifolium.jpg",
    "credit": "(c) Kevin Metcalf, some rights reserved (CC BY-NC), uploaded by Kevin Metcalf",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/128695"
  },
  "Persea borbonia": {
    "src": "/photos/persea-borbonia.jpg",
    "credit": "(c) Carlos G Velazco-Macias, some rights reserved (CC BY-NC), uploaded by Carlos G Velazco-Macias",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/1649672"
  },
  "Prunella vulgaris": {
    "src": "/photos/prunella-vulgaris.jpg",
    "credit": "(c) kenbuchholz, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/52764"
  },
  "Bothriochloa laguroides": {
    "src": "/photos/bothriochloa-laguroides.jpg",
    "credit": "(c) Nicholas Cowey, some rights reserved (CC BY-NC), uploaded by Nicholas Cowey",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/75843"
  },
  "Asclepias linearis": {
    "src": "/photos/asclepias-linearis.jpg",
    "credit": "(c) Bill Freiheit, some rights reserved (CC BY-NC), uploaded by Bill Freiheit",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/158747"
  },
  "Catalpa bignonioides": {
    "src": "/photos/catalpa-bignonioides.jpg",
    "credit": "(c) Matthew Herron, some rights reserved (CC BY-NC), uploaded by Matthew Herron",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/50859"
  },
  "Ipomopsis rubra": {
    "src": "/photos/ipomopsis-rubra.jpg",
    "credit": "(c) CameliaTWU, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/62659"
  },
  "Eriochloa sericea": {
    "src": "/photos/eriochloa-sericea.jpg",
    "credit": "(c) Sam Kieschnick, some rights reserved (CC BY), uploaded by Sam Kieschnick",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/162571"
  },
  "Phyla nodiflora": {
    "src": "/photos/phyla-nodiflora.jpg",
    "credit": "(c) Geoffrey Parks, some rights reserved (CC BY-NC), uploaded by Geoffrey Parks",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/59040"
  },
  "Eysenhardtia texana": {
    "src": "/photos/eysenhardtia-texana.jpg",
    "credit": "(c) Aidan Campos, some rights reserved (CC BY-NC), uploaded by Aidan Campos",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/162927"
  },
  "Wisteria frutescens": {
    "src": "/photos/wisteria-frutescens.jpg",
    "credit": "(c) abelkinser, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/51266"
  },
  "Malvaviscus arboreus": {
    "src": "/photos/malvaviscus-arboreus.jpg",
    "credit": "(c) Rudy Garcia, some rights reserved (CC BY-NC), uploaded by Rudy Garcia",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/120942"
  },
  "Parthenocissus quinquefolia": {
    "src": "/photos/parthenocissus-quinquefolia.jpg",
    "credit": "(c) Suzanne Cadwell, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/50278"
  },
  "Dalea candida": {
    "src": "/photos/dalea-candida.jpg",
    "credit": "(c) cmedmunds, some rights reserved (CC BY-NC), uploaded by cmedmunds",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/81598"
  },
  "Asclepias verticillata": {
    "src": "/photos/asclepias-verticillata.jpg",
    "credit": "(c) eknuth, some rights reserved (CC BY-NC), uploaded by eknuth",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/125379"
  },
  "Monarda fistulosa": {
    "src": "/photos/monarda-fistulosa.jpg",
    "credit": "(c) ziggymom, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/85320"
  },
  "Ruellia humilis": {
    "src": "/photos/ruellia-humilis.jpg",
    "credit": "(c) peganum, some rights reserved (CC BY-SA)",
    "license": "cc-by-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/119651"
  },
  "Croton capitatus": {
    "src": "/photos/croton-capitatus.jpg",
    "credit": "(c) abelkinser, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/observations/55562828"
  },
  "Crinum americanum": {
    "src": "/photos/crinum-americanum.jpg",
    "credit": "(c) jingning42, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/128713"
  },
  "Rudbeckia hirta": {
    "src": "/photos/rudbeckia-hirta.jpg",
    "credit": "no rights reserved, uploaded by Brady Reed",
    "license": "cc0",
    "sourceUrl": "https://www.inaturalist.org/taxa/62741"
  },
  "Cephalanthus occidentalis": {
    "src": "/photos/cephalanthus-occidentalis.jpg",
    "credit": "(c) Michael J. Papay, some rights reserved (CC BY), uploaded by Michael J. Papay",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/52763"
  },
  "Teucrium cubense": {
    "src": "/photos/teucrium-cubense.jpg",
    "credit": "(c) Douglas Goldman, some rights reserved (CC BY-SA), uploaded by Douglas Goldman",
    "license": "cc-by-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/79340"
  },
  "Coreopsis basalis": {
    "src": "/photos/coreopsis-basalis.jpg",
    "credit": "(c) Sarah Towne, some rights reserved (CC BY-NC), uploaded by Sarah Towne",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/160885"
  },
  "Chasmanthium latifolium": {
    "src": "/photos/chasmanthium-latifolium.jpg",
    "credit": "(c) Susan Elliott, some rights reserved (CC BY-NC), uploaded by Susan Elliott",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/84364"
  },
  "Sagittaria lancifolia": {
    "src": "/photos/sagittaria-lancifolia.jpg",
    "credit": "(c) jenarricale, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/observations/96510819"
  },
  "Schizachyrium scoparium": {
    "src": "/photos/schizachyrium-scoparium.jpg",
    "credit": "(c) Scott E Severs, some rights reserved (CC BY-NC), uploaded by Scott E Severs",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/122603"
  },
  "Chasmanthium sessiliflorum": {
    "src": "/photos/chasmanthium-sessiliflorum.jpg",
    "credit": "(c) ksmith, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/84366"
  },
  "Hydrangea quercifolia": {
    "src": "/photos/hydrangea-quercifolia.jpg",
    "credit": "(c) Mauricio Mercadante, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/83156"
  },
  "Chamaecrista fasciculata": {
    "src": "/photos/chamaecrista-fasciculata.jpg",
    "credit": "(c) Fritz Flohr Reynolds, some rights reserved (CC BY-SA)",
    "license": "cc-by-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/127907"
  },
  "Pontederia cordata": {
    "src": "/photos/pontederia-cordata.jpg",
    "credit": "(c) Michael J. Papay, some rights reserved (CC BY), uploaded by Michael J. Papay",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/52599"
  },
  "Agalinis heterophylla": {
    "src": "/photos/agalinis-heterophylla.jpg",
    "credit": "(c) Bryan, some rights reserved (CC BY-NC), uploaded by Bryan",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/142653"
  },
  "Silphium radula": {
    "src": "/photos/silphium-radula.jpg",
    "credit": "(c) Bob O'Kennon, some rights reserved (CC BY-NC), uploaded by Bob O'Kennon",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/128837"
  },
  "Palafoxia rosea": {
    "src": "/photos/palafoxia-rosea.jpg",
    "credit": "(c) ellen hildebrandt, some rights reserved (CC BY-NC), uploaded by ellen hildebrandt",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/166060"
  },
  "Bouteloua curtipendula": {
    "src": "/photos/bouteloua-curtipendula.jpg",
    "credit": "(c) psweet, some rights reserved (CC BY-SA), uploaded by psweet",
    "license": "cc-by-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/75858"
  },
  "Silphium gracile": {
    "src": "/photos/silphium-gracile.jpg",
    "credit": "(c) Mary Spolyar, some rights reserved (CC BY-NC), uploaded by Mary Spolyar",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/168992"
  },
  "Asclepias incarnata": {
    "src": "/photos/asclepias-incarnata.jpg",
    "credit": "(c) aarongunnar, some rights reserved (CC BY), uploaded by aarongunnar",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/125381"
  },
  "Sideroxylon lanuginosum": {
    "src": "/photos/sideroxylon-lanuginosum.jpg",
    "credit": "(c) Ron Stephens, some rights reserved (CC BY-NC), uploaded by Ron Stephens",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/128748"
  },
  "Cyperus esculentus": {
    "src": "/photos/cyperus-esculentus.jpg",
    "credit": "(c) Cin-Ty Lee, some rights reserved (CC BY-NC), uploaded by Cin-Ty Lee",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/76584"
  },
  "Conoclinium coelestinum": {
    "src": "/photos/conoclinium-coelestinum.jpg",
    "credit": "(c) bioblitz_aggregate_account, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/119095"
  },
  "Helianthus annuus": {
    "src": "/photos/helianthus-annuus.jpg",
    "credit": "(c) Emily Scherer, some rights reserved (CC BY-NC), uploaded by Emily Scherer",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/57983"
  },
  "Bromus ciliatus": {
    "src": "/photos/bromus-ciliatus.jpg",
    "credit": "(c) Lynnea Parker, some rights reserved (CC BY-NC), uploaded by Lynnea Parker",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/75899"
  },
  "Rudbeckia maxima": {
    "src": "/photos/rudbeckia-maxima.jpg",
    "credit": "(c) ajenkinsmom, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/128694"
  },
  "Eryngium hookeri": {
    "src": "/photos/eryngium-hookeri.jpg",
    "credit": "(c) mcwildlife, some rights reserved (CC BY-NC-ND), uploaded by mcwildlife",
    "license": "cc-by-nc-nd",
    "sourceUrl": "https://www.inaturalist.org/taxa/130457"
  },
  "Ludwigia octovalvis": {
    "src": "/photos/ludwigia-octovalvis.jpg",
    "credit": "no rights reserved, uploaded by 葉子",
    "license": "cc0",
    "sourceUrl": "https://www.inaturalist.org/taxa/164861"
  },
  "Vernonia missurica": {
    "src": "/photos/vernonia-missurica.jpg",
    "credit": "(c) Jeff Skrentny, some rights reserved (CC BY-NC), uploaded by Jeff Skrentny",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/170182"
  },
  "Liatris acidota": {
    "src": "/photos/liatris-acidota.jpg",
    "credit": "(c) Scott Buckel, some rights reserved (CC BY-NC), uploaded by Scott Buckel",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/164681"
  },
  "Euphorbia bicolor": {
    "src": "/photos/euphorbia-bicolor.jpg",
    "credit": "(c) Marcia Cirillo, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/120585"
  },
  "Juncus effusus": {
    "src": "/photos/juncus-effusus.jpg",
    "credit": "(c) Markus Ackermann, some rights reserved (CC BY-NC), uploaded by Markus Ackermann",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/1536756"
  },
  "Hypericum hypericoides": {
    "src": "/photos/hypericum-hypericoides.jpg",
    "credit": "(c) Michael J. Papay, some rights reserved (CC BY), uploaded by Michael J. Papay",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/120009"
  },
  "Solidago odora": {
    "src": "/photos/solidago-odora.jpg",
    "credit": "(c) Tom Palmer, some rights reserved (CC BY-NC), uploaded by Tom Palmer",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/131183"
  },
  "Hibiscus coccineus": {
    "src": "/photos/hibiscus-coccineus.jpg",
    "credit": "(c) joslyali, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/163763"
  },
  "Bidens aristosa": {
    "src": "/photos/bidens-aristosa.jpg",
    "credit": "(c) amlambert11, some rights reserved (CC BY-NC), uploaded by amlambert11",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/51714"
  },
  "Ageratina altissima": {
    "src": "/photos/ageratina-altissima.jpg",
    "credit": "(c) Dan Mullen, some rights reserved (CC BY-NC-ND)",
    "license": "cc-by-nc-nd",
    "sourceUrl": "https://www.inaturalist.org/taxa/119048"
  },
  "Silphium integrifolium": {
    "src": "/photos/silphium-integrifolium.jpg",
    "credit": "(c) Mark Kluge, some rights reserved (CC BY-NC), uploaded by Mark Kluge",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/168993"
  },
  "Rhus copallinum": {
    "src": "/photos/rhus-copallinum.jpg",
    "credit": "(c) Dendroica cerulea, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/126698"
  },
  "Callicarpa americana": {
    "src": "/photos/callicarpa-americana.jpg",
    "credit": "(c) Alex Abair, some rights reserved (CC BY), uploaded by Alex Abair",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/49193"
  },
  "Andropogon gerardii": {
    "src": "/photos/andropogon-gerardii.jpg",
    "credit": "(c) Kingsbrae Garden, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/121968"
  },
  "Symphyotrichum lateriflorum": {
    "src": "/photos/symphyotrichum-lateriflorum.jpg",
    "credit": "(c) Susan Elliott, some rights reserved (CC BY-NC), uploaded by Susan Elliott",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/122249"
  },
  "Physostegia virginiana": {
    "src": "/photos/physostegia-virginiana.jpg",
    "credit": "(c) benwadejones, some rights reserved (CC BY-NC), uploaded by benwadejones",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/85313"
  },
  "Paspalum floridanum": {
    "src": "/photos/paspalum-floridanum.jpg",
    "credit": "(c) abelkinser, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/166176"
  },
  "Verbesina virginica": {
    "src": "/photos/verbesina-virginica.jpg",
    "credit": "(c) Mark Fishbein, some rights reserved (CC BY-NC), uploaded by Mark Fishbein",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/119982"
  },
  "Symphyotrichum ericoides": {
    "src": "/photos/symphyotrichum-ericoides.jpg",
    "credit": "(c) bcnorval, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/126654"
  },
  "Sorghastrum nutans": {
    "src": "/photos/sorghastrum-nutans.jpg",
    "credit": "(c) Erica Fraley, some rights reserved (CC BY-NC), uploaded by Erica Fraley",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/122608"
  },
  "Symphyotrichum patens": {
    "src": "/photos/symphyotrichum-patens.jpg",
    "credit": "(c) Michael J. Papay, some rights reserved (CC BY), uploaded by Michael J. Papay",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/130810"
  },
  "Tridens strictus": {
    "src": "/photos/tridens-strictus.jpg",
    "credit": "(c) cricketfrog13, some rights reserved (CC BY-NC), uploaded by cricketfrog13",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/169951"
  },
  "Helianthus maximiliani": {
    "src": "/photos/helianthus-maximiliani.jpg",
    "credit": "(c) smwhite, some rights reserved (CC BY-NC), uploaded by smwhite",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/130192"
  },
  "Pityopsis graminifolia": {
    "src": "/photos/pityopsis-graminifolia.jpg",
    "credit": "(c) Eric Duran, some rights reserved (CC BY-NC), uploaded by Eric Duran",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/166939"
  },
  "Bigelowia nudata": {
    "src": "/photos/bigelowia-nudata.jpg",
    "credit": "(c) canoe4nature, some rights reserved (CC BY-NC), uploaded by canoe4nature",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/159267"
  },
  "Liatris elegans": {
    "src": "/photos/liatris-elegans.jpg",
    "credit": "(c) Mike Farley, some rights reserved (CC BY-NC), uploaded by Mike Farley",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/120831"
  },
  "Liatris pycnostachya": {
    "src": "/photos/liatris-pycnostachya.jpg",
    "credit": "(c) Joshua Mayer, some rights reserved (CC BY-SA)",
    "license": "cc-by-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/48691"
  },
  "Tridens flavus": {
    "src": "/photos/tridens-flavus.jpg",
    "credit": "(c) Mary Keim, some rights reserved (CC BY-NC-SA)",
    "license": "cc-by-nc-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/120403"
  },
  "Liatris aspera": {
    "src": "/photos/liatris-aspera.jpg",
    "credit": "(c) aarongunnar, some rights reserved (CC BY), uploaded by aarongunnar",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/130380"
  },
  "Andropogon ternarius": {
    "src": "/photos/andropogon-ternarius.jpg",
    "credit": "(c) Katherine Boyle, some rights reserved (CC BY-NC), uploaded by Katherine Boyle",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/1617178"
  },
  "Saccharum giganteum": {
    "src": "/photos/saccharum-giganteum.jpg",
    "credit": "(c) meleagle, some rights reserved (CC BY-NC)",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/1503466"
  },
  "Helianthus angustifolius": {
    "src": "/photos/helianthus-angustifolius.jpg",
    "credit": "(c) Devin Moon, some rights reserved (CC BY-NC), uploaded by Devin Moon",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/126700"
  },
  "Panicum virgatum": {
    "src": "/photos/panicum-virgatum.jpg",
    "credit": "(c) aarongunnar, some rights reserved (CC BY), uploaded by aarongunnar",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/125727"
  },
  "Solidago tortifolia": {
    "src": "/photos/solidago-tortifolia.jpg",
    "credit": "(c) grbfrog, some rights reserved (CC BY-NC), uploaded by grbfrog",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/169131"
  },
  "Senna lindheimeriana": {
    "src": "/photos/senna-lindheimeriana.jpg",
    "credit": "(c) CompanyInk, some rights reserved (CC BY-NC), uploaded by CompanyInk",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/168843"
  },
  "Symphyotrichum oblongifolium": {
    "src": "/photos/symphyotrichum-oblongifolium.jpg",
    "credit": "(c) aarongunnar, some rights reserved (CC BY), uploaded by aarongunnar",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/119343"
  },
  "Symphyotrichum pratense": {
    "src": "/photos/symphyotrichum-pratense.jpg",
    "credit": "(c) Pterocarya Botany, some rights reserved (CC BY-NC), uploaded by Pterocarya Botany",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/169481"
  },
  "Salvia azurea": {
    "src": "/photos/salvia-azurea.jpg",
    "credit": "(c) Brian Peterson, some rights reserved (CC BY-NC-ND)",
    "license": "cc-by-nc-nd",
    "sourceUrl": "https://www.inaturalist.org/taxa/57121"
  },
  "Ulmus crassifolia": {
    "src": "/photos/ulmus-crassifolia.jpg",
    "credit": "(c) Douglas Goldman, some rights reserved (CC BY-SA), uploaded by Douglas Goldman",
    "license": "cc-by-sa",
    "sourceUrl": "https://www.inaturalist.org/taxa/128823"
  },
  "Zanthoxylum clava-herculis": {
    "src": "/photos/zanthoxylum-clava-herculis.jpg",
    "credit": "(c) Bob O'Kennon, some rights reserved (CC BY-NC), uploaded by Bob O'Kennon",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/119986"
  },
  "Eupatorium serotinum": {
    "src": "/photos/eupatorium-serotinum.jpg",
    "credit": "(c) Michael J. Papay, some rights reserved (CC BY), uploaded by Michael J. Papay",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/52934"
  },
  "Acer rubrum": {
    "src": "/photos/acer-rubrum.jpg",
    "credit": "no rights reserved, uploaded by mefisher",
    "license": "cc0",
    "sourceUrl": "https://www.inaturalist.org/taxa/48098"
  },
  "Rudbeckia texana": {
    "src": "/photos/rudbeckia-texana.jpg",
    "credit": "(c) Bob Romero, some rights reserved (CC BY-NC), uploaded by Bob Romero",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/168208"
  },
  "Hamamelis virginiana": {
    "src": "/photos/hamamelis-virginiana.jpg",
    "credit": "(c) Paul Marcum, some rights reserved (CC BY-NC), uploaded by Paul Marcum",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/51970"
  },
  "Liatris bracteata": {
    "src": "/photos/liatris-bracteata.jpg",
    "credit": "(c) Don Verser, some rights reserved (CC BY-NC), uploaded by Don Verser",
    "license": "cc-by-nc",
    "sourceUrl": "https://www.inaturalist.org/taxa/164682"
  },
  "Muhlenbergia capillaris": {
    "src": "/photos/muhlenbergia-capillaris.jpg",
    "credit": "(c) Lauren McLaurin, some rights reserved (CC BY), uploaded by Lauren McLaurin",
    "license": "cc-by",
    "sourceUrl": "https://www.inaturalist.org/taxa/165543"
  }
};
